###
# GridScan.py
# Top level python module to load the gridscan mainwindow and handle events
# generated by user interactions.
###
from PyQt4 import QtCore, QtGui, uic
from epics import caget, cainfo, caput
import sys

class gridscan(QtGui.QMainWindow):

    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = uic.loadUi("C:\Users\przem\workdir\GridScan\gridscan_mainwin.ui", self)
        print "We get to here "
        val = caget ("Dera:m1.VAL")
        print val
        s="%f"%(val)
        self.ui.x_CurLocLE.setText(s)
        self.ui.x_CenterLocLE.setText(s)

        self.ui.x_IncLE.setText(".01")



if __name__=='__main__':
    app = QtGui.QApplication(sys.argv)
    GS = gridscan()
    GS.show()
    sys.exit(app.exec_())

