###
# GridScan.py
# Top level python module to load the gridscan mainwindow and handle events
# generated by user interactions.
###
from PyQt4 import QtCore, QtGui, uic
from epics import caget, cainfo, caput
from MyCAEpics import *
import sys
import time

class gridscan(QtGui.QMainWindow):

    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = uic.loadUi("gridscan_mainwin.ui", self)
        caput ("Dera:m1.VAL", 5.1)
        caput ("Dera:m2.VAL", 2.7)
        print "We get to here "
        curval = caget ("Dera:m1.VAL")
        s="%7.4f"%(curval)
        print "M1 position is : ", s
        self.ui.x_CurLocLE.setText(s)
        self.ui.x_RangeLE.setText (".2")
        self.ui.x_CenterLocLE.setText(s)
        self.ui.x_NStepsLE.setText("10")
        self.ui.x_MoveLocLE.setText(s)
        self.ca = MyCAEpics ()
        #self.connect (self.ca, self.ca.update_position, self,
        #              QtCore.pyqtSlot(self.updateMotors))
        self.ca.update_position.connect (self.update_motors)
        self.ui.x_MoveButton.clicked.connect (self.move_x_motor)
        self.ui.y_MoveButton.clicked.connect (self.move_y_motor)
        self.ui.StartScanButton.clicked.connect (self.start_scan)

    def update_motors (self, mot_num, pos) :
        s="%6.3f"%pos
        print "move motor : %d to position %f"%(mot_num, pos)
        if (mot_num==0) :
            self.ui.x_CurLocLE.setText(s)
        if (mot_num==1) :
            self.ui.y_CurLocLE.setText (s)
        #if mot_num == 0 :

    def move_x_motor (self) :
        val = self.ui.x_MoveLocLE.text().toFloat()[0]
        print "move motor : "
        self.ca.move_motor (0, val)
        time.sleep (1)
        val = self.ca.get_position (0)
        s="%5.3f"%val
        self.ui.x_CurLocLE.setText(s)


    def move_y_motor (self) :
        val = self.ui.y_MoveLocLE.text().toFloat()[0]
        print "move motor : "
        self.ca.move_motor (0, val)
        time.sleep (1)
        val = self.ca.get_position (1)
        s="%5.3f"%val
        self.ui.y_CurLocLE.setText(s)

    def start_scan (self) :
        #self.ca.set_pasfams ()
        x0 = self.ui.x_CenterLocLE.text().toFloat()[0]
        xrange = self.ui.x_RangeLE.text().toFloat()[0]
        xsteps = self.ui.x_NStepsLE.text().toInt()[0]

        y0 = self.ui.y_CenterLocLE.text().toFloat()[0]
        yrange = self.ui.y_RangeLE.text().toFloat()[0]
        ysteps = self.ui.y_NStepsLE.text().toInt()[0]

        self.ca.set_params( x0, xrange, xsteps, y0, yrange, ysteps)
        acquisition_time = self.ui.acquisitionTimeLE.text().toInt()[0]
        outprefix = self.ui.outprefLE.text()
        self.ca.set_acquisition_params (outprefix, acquisition_time)

        self.ca.start ()


if __name__=='__main__':
    app = QtGui.QApplication(sys.argv)
    GS = gridscan()
    GS.show()
    sys.exit(app.exec_())

